variables:
  TESTDIR: "${CI_PROJECT_DIR}/testdir"

before_script:
  # Common part to setup vars
  - source /cvmfs/grid.cern.ch/etc/profile.d/setup-cvmfs-ui.sh
  - source /cvmfs/cms.cern.ch/cmsset_default.sh
  - source ${CI_PROJECT_DIR}/scripts/pre_install.sh  # setup general vars
  - source ${CI_PROJECT_DIR}/scripts/to_test.sh
  # Update PRID env var if it wasn't already set & add to vars
  - "[ -z \"$PRID\" ] && python scripts/get_pr_id.py --id $PRNUM --dumpFilename ${CI_PROJECT_DIR}/scripts/to_test.sh --dumpVarname PRID && source ${CI_PROJECT_DIR}/scripts/to_test.sh"


get-uhh:
  # Get the ref & modified versions of UHH2 that is used in later steps along with diff
  tags:
  - cvmfs
  stage: getit
  except:
    - master
  script:
    - source ${CI_PROJECT_DIR}/scripts/notify_github.sh "start"
    - source ${CI_PROJECT_DIR}/scripts/get_uhh_ref_and_new.sh || source ${CI_PROJECT_DIR}/scripts/notify_github.sh "failed" "Failed to checkout UHH2 & merge PR"
  artifacts:
    paths:
      - UHH2
    expire_in: 2 days


build-new:
  # Build the new user's version
  tags:
  - cvmfs
  stage: build
  dependencies:
    - get-uhh
  except:
    - master
  artifacts:
    name: ${CI_COMMIT_REF_NAME}-new
    expire_in: 6 mos
    paths:
      - ${TESTDIR}/all_${CI_COMMIT_REF_NAME}.tgz
      - ${TESTDIR}/deploy_script_all_${CI_COMMIT_REF_NAME}.sh
  script:
    - yum install -y libtool  # needed for autoreconf when setting up fastjet
    - cd UHH2 && git checkout ${LOCALBRANCH} && cd .. # Use the modified branch
    - mkdir -p ${TESTDIR} && cd ${TESTDIR}
    # deploy CMSSW, UHH
    - source ${CI_PROJECT_DIR}/UHH2/scripts/install.sh || source ${CI_PROJECT_DIR}/scripts/notify_github.sh "failed" "install.sh failed, please check log"
    - source ${CI_PROJECT_DIR}/scripts/replace_UHH.sh  # Use the UHH2 version we checked out
    # Compile everything
    - source ${CI_PROJECT_DIR}/scripts/post_install.sh  || source ${CI_PROJECT_DIR}/scripts/notify_github.sh "failed" "Compilation of SFrame / UHH2 failed, please check log"
    # Check the python is even valid
    - cd ${CMSSW_BASE}/src/UHH2/core/python
    - for f in ntuple*.py; do echo "$f"; python "$f" || source ${CI_PROJECT_DIR}/scripts/notify_github.sh "failed" 'Encountered invalid python in ntuplewriter* scripts' ; done
    # Tar up CMSSW & SFrame
    - cd ${TESTDIR} && python ${CI_PROJECT_DIR}/scripts/tarballEntireRelease.py -o ${TESTDIR}/all_${CI_COMMIT_REF_NAME}.tgz


build-ref:
  # Build the reference UHH version (set in the install.sh in UHH2)
  # so we don't need the replace_UHH.sh
  tags:
  - cvmfs
  stage: build
  dependencies:
    - get-uhh
  except:
    - master
  artifacts:
    name: ${CI_COMMIT_REF_NAME}-ref
    expire_in: 6 mos
    paths:
      - ${TESTDIR}/all_ref.tgz
      - ${TESTDIR}/deploy_script_all_ref.sh
  script:
    - yum install -y libtool  # needed for autoreconf when setting up fastjet
    - cd UHH2 && git checkout ${REFBRANCH} && cd .. # Use the reference branch
    - mkdir -p ${TESTDIR} && cd ${TESTDIR}
    - source ${CI_PROJECT_DIR}/UHH2/scripts/install.sh # deploy CMSSW, UHH
    - source ${CI_PROJECT_DIR}/scripts/post_install.sh  # Compile everything
    # Check the python is even valid
    # - cd ${CMSSW_BASE}/src/UHH2/core/python
    # - for f in ntuple*.py; do python "$f"; done
    # Tar up CMSSW & SFrame
    - cd ${TESTDIR} && python ${CI_PROJECT_DIR}/scripts/tarballEntireRelease.py -o ${TESTDIR}/all_ref.tgz


cmsrun-2018-data-new:
  # Run 2018 data on PR
  tags:
  - cvmfs
  stage: cmsrun
  dependencies:
    - build-new
  except:
    - master
  script:
    - cd ${TESTDIR} && source deploy_script_all_${CI_COMMIT_REF_NAME}.sh && cd ${TESTDIR}
    - python ${CMSSW_BASE}/python/UHH2/core/ntuplewriter_data_2018.py maxEvents=500 wantSummary=1 outputFile="Ntuple_2018_data_new.root"


success:
  tags:
    - cvmfs
  stage: end
  when: on_success
  except:
    - master
  script:
    - source ${CI_PROJECT_DIR}/scripts/notify_github.sh "passed" "Compilations & tests successful"

failure:
  tags:
    - cvmfs
  stage: end
  when: on_failure
  except:
    - master
  script:
    - source ${CI_PROJECT_DIR}/scripts/notify_github.sh "failed" "Compilations and/or tests failed, please check logs"


stages:
  - getit
  - build
  - cmsrun
  - end
