before_script:
  # Common part to setup vars, get the version of UHH in the PR
  - source /cvmfs/grid.cern.ch/etc/profile.d/setup-cvmfs-ui.sh
  - source /cvmfs/cms.cern.ch/cmsset_default.sh
  - yum install -y libtool  # needed for autoreconf when setting up fastjet
  - source ${CI_PROJECT_DIR}/scripts/pre_install.sh  # setup general vars
  - source ${CI_PROJECT_DIR}/to_test.sh
  - source ${CI_PROJECT_DIR}/scripts/get_uhh.sh # get the desired version of UHH2

build-pr:
  # Build the user's PR
  tags:
  - cvmfs
  stage: build
  script:
    - export TESTDIR=${CI_PROJECT_DIR}/testdir
    - mkdir ${TESTDIR} && cd ${TESTDIR}
    - source ${CI_PROJECT_DIR}/UHH2/scripts/install.sh # deploy CMSSW, UHH
    - source ${CI_PROJECT_DIR}/scripts/replace_UHH.sh  # Use the UHH2 PR version
    - source ${CI_PROJECT_DIR}/scripts/post_install.sh  # Compile everything
    # Check the python is even valid
    - cd ${CMSSW_BASE}/src/UHH2/core/python
    - python ntuplewriter.py


build-ref:
  # Build the reference UHH version (set in the install.sh in UHH2)
  tags:
  - cvmfs
  stage: build
  script:
    - export TESTDIR=${CI_PROJECT_DIR}/testdir
    - mkdir ${TESTDIR} && cd ${TESTDIR}
    - source ${CI_PROJECT_DIR}/UHH2/scripts/install.sh # deploy CMSSW, UHH
    - source ${CI_PROJECT_DIR}/scripts/post_install.sh  # Compile everything
    # Check the python is even valid
    - cd ${CMSSW_BASE}/src/UHH2/core/python
    - python ntuplewriter.py

stages:
  - build
