variables:
  GIT_STRATEGY: clone   # use clone and not fetch otherwise rerunning jobs after a push fails
  CMSSW_GIT_REFERENCE: "${CI_PROJECT_DIR}/cmssw.git"
  TESTDIR: "${CI_PROJECT_DIR}/testdir"
  SCRIPTDIR: "${CI_PROJECT_DIR}/scripts"
  GITHUB_QUIET: 0  #  1 to turn off github posts, 0 otherwise
  PRNUM: "1359"
  REFBRANCH: "RunII_102X_v1"
  REMOTEBRANCH: "pull/1359/head"
  LOCALBRANCH: "test1359"
  PRID: "MDExOlB1bGxSZXF1ZXN0MzAwMzQ1MTI0"
  MAKENTUPLES: "1"
#@TESTVARS@

# DO NOT DELETE THE TESTVARS COMMENT - gets replaced for each branch with necessary variables

before_script:
  # Common part to setup vars
  - source /cvmfs/grid.cern.ch/etc/profile.d/setup-cvmfs-ui.sh
  - source /cvmfs/cms.cern.ch/cmsset_default.sh
  - source ${SCRIPTDIR}/pre_install.sh  # setup general vars
  # Update PRID env var if it wasn't already set & add to vars
  - "[ -z \"$PRID\" ] && python scripts/get_pr_id.py --id $PRNUM --dumpFilename ${SCRIPTDIR}/to_test.sh --dumpVarname PRID && source ${SCRIPTDIR}/to_test.sh"
  - "[ -e ${SCRIPTDIR}/to_test.sh ] && source ${SCRIPTDIR}/to_test.sh"

.job_template: &job_definition  # Common items used for all jobs
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:slc6 # need this as the default in gitlab is now SLC7
  tags:
  - cvmfs

get-uhh:
  # Get the ref & modified versions of UHH2 that is used in later steps along with diff
  <<: *job_definition
  stage: getit
  except:
    - master
  script:
    - source ${SCRIPTDIR}/notify_github.sh "start"
    - source ${SCRIPTDIR}/add_label.sh $REFBRANCH
    - source ${SCRIPTDIR}/get_uhh_ref_and_new.sh || source ${SCRIPTDIR}/notify_github.sh "failed" "Failed to checkout UHH2 & merge PR"
  artifacts:
    paths:
      - UHH2
    expire_in: 2 days

# -----------------------------------------------------------------------------
# BUILD & COMPILE JOBS
# -----------------------------------------------------------------------------
build-new:
  # Build the new user's version
  <<: *job_definition
  stage: build
  dependencies:
    - get-uhh
  except:
    - master
  artifacts:
    name: ${CI_COMMIT_REF_NAME}-new-setup
    expire_in: 6 mos
    paths:
      - ${TESTDIR}/all_${CI_COMMIT_REF_NAME}.tgz
      - ${TESTDIR}/deploy_script_all_${CI_COMMIT_REF_NAME}.sh
  script:
    - yum install -y libtool  # needed for autoreconf when setting up fastjet
    - cd UHH2 && git checkout ${LOCALBRANCH} && cd .. # Use the modified branch
    - mkdir -p ${TESTDIR} && cd ${TESTDIR}
    # deploy CMSSW, UHH
    - source ${CI_PROJECT_DIR}/UHH2/scripts/install.sh || source ${SCRIPTDIR}/notify_github.sh "failed" "install.sh failed, please check log"
    - source ${SCRIPTDIR}/replace_UHH.sh  # Use the UHH2 version we checked out
    # Compile everything
    - source ${SCRIPTDIR}/post_install.sh || source ${SCRIPTDIR}/notify_github.sh "failed" "Compilation of SFrame / UHH2 failed, please check log"
    - source ${SCRIPTDIR}/post_comment.sh "Compilation with PR successful"
    # Check the python is even valid
    - cd ${CMSSW_BASE}/src/UHH2/core/python
    - for f in ntuple*.py; do echo "$f"; python "$f" || source ${SCRIPTDIR}/notify_github.sh "failed" 'Encountered invalid python in ntuplewriter* scripts' ; done
    # Check the CRAB tarball size
    - source /cvmfs/cms.cern.ch/crab3/crab.sh; cd ${CMSSW_BASE}/src/UHH2/scripts/crab;
      python ${SCRIPTDIR}/makeCheckCrabTarball.py --output testTarball.tgz || source ${SCRIPTDIR}/post_comment.sh "CRAB tarball creation failed or exceeded size limit"; rm testTarball.tgz
    # Tar up CMSSW & SFrame but only for 102X jobs where we actually run cmsrun jobs
    - if [[ $REFBRANCH == "RunII_102X"* ]]; then cd ${TESTDIR} && python ${SCRIPTDIR}/tarballEntireRelease.py -o ${TESTDIR}/all_${CI_COMMIT_REF_NAME}.tgz; fi


build-ref:
  # Build the reference UHH version (set in the install.sh in UHH2)
  # so we don't need the replace_UHH.sh
  <<: *job_definition
  stage: build
  dependencies:
    - get-uhh
  only:
    variables:
      - $MAKENTUPLES == "1"
  except:
    - master
  artifacts:
    name: ${CI_COMMIT_REF_NAME}-ref-setup
    expire_in: 6 mos
    paths:
      - ${TESTDIR}/all_ref.tgz
      - ${TESTDIR}/deploy_script_all_ref.sh
  script:
    - yum install -y libtool  # needed for autoreconf when setting up fastjet
    - cd UHH2 && git checkout ${REFBRANCH} && cd .. # Use the reference branch
    - mkdir -p ${TESTDIR} && cd ${TESTDIR}
    - source ${CI_PROJECT_DIR}/UHH2/scripts/install.sh # deploy CMSSW, UHH
    - source ${SCRIPTDIR}/post_install.sh  # Compile everything
    - if [[ $REFBRANCH == "RunII_102X"* ]]; then cd ${TESTDIR} && python ${SCRIPTDIR}/tarballEntireRelease.py -o ${TESTDIR}/all_ref.tgz; fi  # Tar up CMSSW & SFrame, only if doing cmsrun jobs


# Logic for determining MAKENTUPLES in openshiftapp.py
# Based on refbranch, and whether or not user included magic words in PR text.
# Note that if you add only/except in the stage iteself, it will ignore this
.makentuple-template: &make-ntuples
  only:
    variables:
      - $MAKENTUPLES == "1"
  except:
    - master

# cmsRun job templates
.cmsrun-template: &cmsrun
  <<: *job_definition
  stage: cmsrun
  <<: *make-ntuples
  retry: 2
  artifacts:
    name: ${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}
    expire_in: 6 mos
    paths:
      - ${TESTDIR}/Ntuple*.root
      - ${TESTDIR}/log*.txt
      - ${TESTDIR}/*.json

.cmsrun-new-template: &cmsrun-new
  # Run cmsRun on PR
  <<: *cmsrun
  dependencies:
    - build-new

.cmsrun-ref-template: &cmsrun-ref
  # Run cmsRun on reference setup
  # we allow this one to fail, since the PR might be fixing some error in the repo
  <<: *cmsrun
  dependencies:
    - build-ref
  allow_failure: true

# Comparison & webpage job between ntuples
# Must set dependencies manually, including build-new
.compare-webpage-template: &compare-webpage
  <<: *job_definition
  stage: compare
  <<: *make-ntuples
  artifacts:
    name: webpage-${CI_JOB_NAME}
    paths:
      - public
      - ${TESTDIR}/*.json
  script:
    # needed to get libSM
    - yum install -y libXext libSM libXrender
    # Deploy our release to get a newer version of python etc, check packages
    - cd ${TESTDIR} && source deploy_script_all_${CI_COMMIT_REF_NAME}.sh && cd ${TESTDIR}
    - pip install --user -r ${CI_PROJECT_DIR}/requirements_local.txt
    # Compare the 2 ntuples, making plots
    - source ${SCRIPTDIR}/makeAllNtupleComparisons.sh
    # generate the webpage here since we have all the necessary inputs
    # (plots, timing json, size json)
    - ls ${TESTDIR}
    - source ${SCRIPTDIR}/makeAllWebpages.sh

# Deploy the pages generated to DFS
# contents actually generated in compare-webpage job
# https://gitlab.cern.ch/gitlabci-examples/deploy_dfs/
# requires vars DFS_WEBSITE_NAME, DFS_WEBSITE_USERNAME, DFS_WEBSITE_PASSWORD
# Must set dependencies to compare job
# We do this in separate jobs since the upload is slow, so we want to
# parallelise it as much as possible
.dfsdeploy-template: &dfs-deploy
  stage: deploy
  <<: *make-ntuples
  # Custom docker image providing the needed tools to deploy in DFS
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
    # Script that performs the deploy to DFS. Makes use of the variables defined in the project
    # It will not sync the generated content with the folder in DFS (risk of deleting DFS management files)
    # It will just override the contents of DFS or copy new files
    # redirect to dev null otherwise too much log text
    - deploy-dfs > /dev/null 2>&1
    # do not run any globally defined before_script or after_script for this step
  before_script: []
  after_script: []

# -----------------------------------------------------------------------------
# CMS RUN JOBS
# -----------------------------------------------------------------------------
# Each {era, type} should have a new job (to run on PR),
# a ref job (to run on current HEAD), a comparison & webpage maker job,
# and a dfs uploader job

cmsrun-2018-data-new:
  # Run 2018 data on PR
  <<: *cmsrun-new
  script:
    - cd ${TESTDIR} && source deploy_script_all_${CI_COMMIT_REF_NAME}.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2018 --isData --append "_new"

cmsrun-2018-data-ref:
  # Run 2018 data on reference
  <<: *cmsrun-ref
  script:
    - cd ${TESTDIR} && source deploy_script_all_ref.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2018 --isData --append "_ref"

compare-webpage-2018-data:
  <<: *compare-webpage
  dependencies:
    - build-new
    - cmsrun-2018-data-new
    - cmsrun-2018-data-ref

dfsdeploy-2018-data:
  <<: *dfs-deploy
  dependencies:
    - compare-webpage-2018-data

#-------------------------------------------------------------------------------

cmsrun-2018-mc-new:
  # Run 2018 mc on PR
  <<: *cmsrun-new
  script:
    - cd ${TESTDIR} && source deploy_script_all_${CI_COMMIT_REF_NAME}.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2018 --append "_new"

cmsrun-2018-mc-ref:
  # Run 2018 mc on reference
  <<: *cmsrun-ref
  script:
    - cd ${TESTDIR} && source deploy_script_all_ref.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2018 --append "_ref"

compare-webpage-2018-mc:
  <<: *compare-webpage
  dependencies:
    - build-new
    - cmsrun-2018-mc-new
    - cmsrun-2018-mc-ref

dfsdeploy-2018-mc:
  <<: *dfs-deploy
  dependencies:
    - compare-webpage-2018-mc

#-------------------------------------------------------------------------------

cmsrun-2017v2-data-new:
  # Run 2017v2 data on PR
  <<: *cmsrun-new
  script:
    - cd ${TESTDIR} && source deploy_script_all_${CI_COMMIT_REF_NAME}.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2017v2 --isData --append "_new"

cmsrun-2017v2-data-ref:
  # Run 2017v2 data on reference
  <<: *cmsrun-ref
  script:
    - cd ${TESTDIR} && source deploy_script_all_ref.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2017v2 --isData --append "_ref"

compare-webpage-2017v2-data:
  <<: *compare-webpage
  dependencies:
    - build-new
    - cmsrun-2017v2-data-new
    - cmsrun-2017v2-data-ref

dfsdeploy-2017v2-data:
  <<: *dfs-deploy
  dependencies:
    - compare-webpage-2017v2-data

#-------------------------------------------------------------------------------

cmsrun-2017v2-mc-new:
  # Run 2017v2 mc on PR
  <<: *cmsrun-new
  script:
    - cd ${TESTDIR} && source deploy_script_all_${CI_COMMIT_REF_NAME}.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2017v2 --append "_new"

cmsrun-2017v2-mc-ref:
  # Run 2017v2 mc on reference
  <<: *cmsrun-ref
  script:
    - cd ${TESTDIR} && source deploy_script_all_ref.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2017v2 --append "_ref"

compare-webpage-2017v2-mc:
  <<: *compare-webpage
  dependencies:
    - build-new
    - cmsrun-2017v2-mc-new
    - cmsrun-2017v2-mc-ref

dfsdeploy-2017v2-mc:
  <<: *dfs-deploy
  dependencies:
    - compare-webpage-2017v2-mc

#-------------------------------------------------------------------------------
# NB no 2017v1 data jobs as no one uses that dataset

cmsrun-2017v1-mc-new:
  # Run 2017v1 mc on PR
  <<: *cmsrun-new
  script:
    - cd ${TESTDIR} && source deploy_script_all_${CI_COMMIT_REF_NAME}.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2017v1 --append "_new"

cmsrun-2017v1-mc-ref:
  # Run 2017v1 mc on reference
  <<: *cmsrun-ref
  script:
    - cd ${TESTDIR} && source deploy_script_all_ref.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2017v1 --append "_ref"

compare-webpage-2017v1-mc:
  <<: *compare-webpage
  dependencies:
    - build-new
    - cmsrun-2017v1-mc-new
    - cmsrun-2017v1-mc-ref

dfsdeploy-2017v1-mc:
  <<: *dfs-deploy
  dependencies:
    - compare-webpage-2017v1-mc

#-------------------------------------------------------------------------------

cmsrun-2016v3-data-new:
  # Run 2016v3 data on PR
  <<: *cmsrun-new
  script:
    - cd ${TESTDIR} && source deploy_script_all_${CI_COMMIT_REF_NAME}.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2016v3 --isData --append "_new"

cmsrun-2016v3-data-ref:
  # Run 2016v3 data on reference
  <<: *cmsrun-ref
  script:
    - cd ${TESTDIR} && source deploy_script_all_ref.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2016v3 --isData --append "_ref"

compare-webpage-2016v3-data:
  <<: *compare-webpage
  dependencies:
    - build-new
    - cmsrun-2016v3-data-new
    - cmsrun-2016v3-data-ref

dfsdeploy-2016v3-data:
  <<: *dfs-deploy
  dependencies:
    - compare-webpage-2016v3-data

#-------------------------------------------------------------------------------

cmsrun-2016v3-mc-new:
  # Run 2016v3 mc on PR
  <<: *cmsrun-new
  script:
    - cd ${TESTDIR} && source deploy_script_all_${CI_COMMIT_REF_NAME}.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2016v3 --append "_new"

cmsrun-2016v3-mc-ref:
  # Run 2016v3 mc on reference
  <<: *cmsrun-ref
  script:
    - cd ${TESTDIR} && source deploy_script_all_ref.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2016v3 --append "_ref"

compare-webpage-2016v3-mc:
  <<: *compare-webpage
  dependencies:
    - build-new
    - cmsrun-2016v3-mc-new
    - cmsrun-2016v3-mc-ref

dfsdeploy-2016v3-mc:
  <<: *dfs-deploy
  dependencies:
    - compare-webpage-2016v3-mc

#-------------------------------------------------------------------------------

cmsrun-2016v2-data-new:
  # Run 2016v2 data on PR
  <<: *cmsrun-new
  script:
    - cd ${TESTDIR} && source deploy_script_all_${CI_COMMIT_REF_NAME}.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2016v2 --isData --append "_new"

cmsrun-2016v2-data-ref:
  # Run 2016v2 data on reference
  <<: *cmsrun-ref
  script:
    - cd ${TESTDIR} && source deploy_script_all_ref.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2016v2 --isData --append "_ref"

compare-webpage-2016v2-data:
  <<: *compare-webpage
  dependencies:
    - build-new
    - cmsrun-2016v2-data-new
    - cmsrun-2016v2-data-ref

dfsdeploy-2016v2-data:
  <<: *dfs-deploy
  dependencies:
    - compare-webpage-2016v2-data

#-------------------------------------------------------------------------------

cmsrun-2016v2-mc-new:
  # Run 2016v2 mc on PR
  <<: *cmsrun-new
  script:
    - cd ${TESTDIR} && source deploy_script_all_${CI_COMMIT_REF_NAME}.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2016v2 --append "_new"

cmsrun-2016v2-mc-ref:
  # Run 2016v2 mc on reference
  <<: *cmsrun-ref
  script:
    - cd ${TESTDIR} && source deploy_script_all_ref.sh && cd ${TESTDIR}
    - python ${SCRIPTDIR}/cmsrun_jobs.py --year 2016v2 --append "_ref"

compare-webpage-2016v2-mc:
  <<: *compare-webpage
  dependencies:
    - build-new
    - cmsrun-2016v2-mc-new
    - cmsrun-2016v2-mc-ref

dfsdeploy-2016v2-mc:
  <<: *dfs-deploy
  dependencies:
    - compare-webpage-2016v2-mc

# -----------------------------------------------------------------------------
# REVIEW
# -----------------------------------------------------------------------------
review-ntuples:
  <<: *job_definition
  stage: review
  <<: *make-ntuples
  dependencies:
    - build-new
    - cmsrun-2018-data-new
    - cmsrun-2018-data-ref
    - compare-webpage-2018-data
    - cmsrun-2018-mc-new
    - cmsrun-2018-mc-ref
    - compare-webpage-2018-mc
    - cmsrun-2017v2-data-new
    - cmsrun-2017v2-data-ref
    - compare-webpage-2017v2-data
    - cmsrun-2017v2-mc-new
    - cmsrun-2017v2-mc-ref
    - compare-webpage-2017v2-mc
    - cmsrun-2017v1-mc-new
    - cmsrun-2017v1-mc-ref
    - compare-webpage-2017v1-mc
    - cmsrun-2016v3-data-new
    - cmsrun-2016v3-data-ref
    - compare-webpage-2016v3-data
    - cmsrun-2016v3-mc-new
    - cmsrun-2016v3-mc-ref
    - compare-webpage-2016v3-mc
    - cmsrun-2016v2-data-new
    - cmsrun-2016v2-data-ref
    - compare-webpage-2016v2-data
    - cmsrun-2016v2-mc-new
    - cmsrun-2016v2-mc-ref
    - compare-webpage-2016v2-mc
  script:
    # Deploy our release to get a newer version of python etc, check packages
    - cd ${TESTDIR} && source deploy_script_all_${CI_COMMIT_REF_NAME}.sh && cd ${TESTDIR}
    - pip install --user -r ${CI_PROJECT_DIR}/requirements_local.txt
    # Make the markdown tables to go into PR text
    - source ${SCRIPTDIR}/makeTimingTable.sh
    - source ${SCRIPTDIR}/makeSizeTable.sh
    - source ${SCRIPTDIR}/makeNtupleComparisonTableAll.sh
    # do PR review with all the necessary inputs
    - ls ${TESTDIR}
    - python ${SCRIPTDIR}/doPRReview.py --timing ${TESTDIR}/timing_report.md --size ${TESTDIR}/size_report.md --plots ${TESTDIR}/ntuple_report.md


# -----------------------------------------------------------------------------
# FINISHING UP STAGES
# -----------------------------------------------------------------------------
success:
  <<: *job_definition
  stage: end
  when: on_success
  except:
    refs:
      - master
    variables:
      - $MAKENTUPLES == "1"  # only do this if no PR review
  # don't need artifacts
  dependencies:
  script:
    - source ${SCRIPTDIR}/notify_github.sh "passed" "Compilations & tests successful"

failure:
  <<: *job_definition
  stage: end
  when: on_failure
  except:
    - master
  # don't need artifacts
  dependencies:
  script:
    - source ${SCRIPTDIR}/notify_github.sh "failed" "Compilations and/or tests failed, please check logs"


stages:
  - getit
  - build
  - cmsrun
  - compare
  - deploy
  - review
  - end
