uhh2:
  tags:
  - cvmfs

  # cache:
  #   paths:
  #   - ${CI_PROJECT_DIR}/cmssw.git

  before_script:
    - source /cvmfs/grid.cern.ch/etc/profile.d/setup-cvmfs-ui.sh
    - source /cvmfs/cms.cern.ch/cmsset_default.sh
    - yum install -y libtool  # necessary for autoreconf
    
    - source ${CI_PROJECT_DIR}/scripts/pre_install.sh  # setup general vars
    - source ${CI_PROJECT_DIR}/to_test.sh
    - source ${CI_PROJECT_DIR}/scripts/get_uhh.sh # get the desired version of UHH2
    - export TESTDIR=${CI_PROJECT_DIR}/testdir
    - mkdir ${TESTDIR}
    - cd ${TESTDIR}
    - source ${CI_PROJECT_DIR}/UHH2/scripts/install.sh # deploy CMSSW, UHH
    - source ${CI_PROJECT_DIR}/scripts/post_install.sh  # Use the UHH2 PR, compile everything
  script:
    - cd ${CMSSW_BASE}/src/UHH2/core/python
    # Check the python is even valid
    - python ntuplewriter.py
