before_script:
  # Common part to setup vars
  - source /cvmfs/grid.cern.ch/etc/profile.d/setup-cvmfs-ui.sh
  - source /cvmfs/cms.cern.ch/cmsset_default.sh
  - source ${CI_PROJECT_DIR}/scripts/pre_install.sh  # setup general vars
  - source ${CI_PROJECT_DIR}/scripts/get_pr_id.sh
  - source ${CI_PROJECT_DIR}/scripts/to_test.sh


get-uhh:
  # Get the ref & modified versions of UHH2 that is used in later steps along with diff
  tags:
  - cvmfs
  stage: getit
  except:
    - master
  script:
    - source ${CI_PROJECT_DIR}/scripts/get_uhh_ref_and_new.sh
  artifacts:
    paths:
      - UHH2
    expire_in: 2 days


build-new:
  # Build the new user's version
  tags:
  - cvmfs
  stage: build
  script:
    - yum install -y libtool  # needed for autoreconf when setting up fastjet
    - cd UHH2 && git checkout ${LOCALBRANCH} && cd .. # Use the modified branch
    - export TESTDIR=${CI_PROJECT_DIR}/testdir
    - mkdir ${TESTDIR} && cd ${TESTDIR}
    - source ${CI_PROJECT_DIR}/UHH2/scripts/install.sh # deploy CMSSW, UHH
    - source ${CI_PROJECT_DIR}/scripts/replace_UHH.sh  # Use the UHH2 version we checked out
    - source ${CI_PROJECT_DIR}/scripts/post_install.sh  # Compile everything
    # Check the python is even valid
    - cd ${CMSSW_BASE}/src/UHH2/core/python
    - for f in ntuple*.py; do python "$f"; done


build-ref:
  # Build the reference UHH version (set in the install.sh in UHH2)
  # so we don't need the replace_UHH.sh
  tags:
  - cvmfs
  stage: build
  script:
    - yum install -y libtool  # needed for autoreconf when setting up fastjet
    - cd UHH2 && git checkout ${REFBRANCH} && cd .. # Use the reference branch
    - export TESTDIR=${CI_PROJECT_DIR}/testdir
    - mkdir ${TESTDIR} && cd ${TESTDIR}
    - source ${CI_PROJECT_DIR}/UHH2/scripts/install.sh # deploy CMSSW, UHH
    - source ${CI_PROJECT_DIR}/scripts/post_install.sh  # Compile everything
    # Check the python is even valid
    - cd ${CMSSW_BASE}/src/UHH2/core/python
    - for f in ntuple*.py; do python "$f"; done

stages:
  - getit
  - build
